language: php
php:
  - "5.3.3"
  - "5.3"
  - "5.4"
before_script:
  - composer require squizlabs/php_codesniffer:~1.4
  - composer install
  - sudo apt-get install -qq php5-radius
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 tests
