<?php
/**
 * ZF2 Authentication Adapter Radius Attributes
 *
 * @category   Authentication
 * @package    Fing
 * @copyright  Copyright (c) 2014 fzipi
 * @license    http://opensource.org/licenses/MIT The MIT License
 * @author Felipe Weckx <felipe@weckx.net>
 * @author Felipe Zipitria <fzipi@fing.edu.uy>
 */

namespace Fing\Authentication\Adapter\Radius;

/**
 * Attributes from Radius package
 *
 * @author Felipe Zipitria <fzipi@fing.edu.uy>
 */
class Attributes
{
    private $_attributes = array(
        "User-Name" => 1,
        "User-Password" => 2,
        "CHAP-Password" => 3,
        "NAS-IP-Address" => 4,
        "NAS-Port" => 5,
        "Service-Type" => 6,
        "Framed-Protocol" => 7,
        "Framed-IP-Address" => 8,
        "Framed-IP-Netmask" => 9,
        "Framed-Routing" => 10,
        "Filter-Id" => 11,
        "Framed-MTU" => 12,
        "Framed-Compression" => 13,
        "Login-IP-Host" => 14,
        "Login-Service" => 15,
        "Login-TCP-Port" => 16,
        "Reply-Message" => 18,
        "Callback-Number" => 19,
        "Callback-Id" => 20,
        "Framed-Route" => 22,
        "Framed-IPX-Network" => 23,
        "State" => 24,
        "Class" => 25,
        "Vendor-Specific" => 26,
        "Session-Timeout" => 27,
        "Idle-Timeout" => 28,
        "Termination-Action" => 29,
        "Called-Station-Id" => 30,
        "Calling-Station-Id" => 31,
        "NAS-Identifier" => 32,
        "Proxy-State" => 33,
        "Login-LAT-Service" => 34,
        "Login-LAT-Node" => 35,
        "Login-LAT-Group" => 36,
        "Framed-AppleTalk-Link" => 37,
        "Framed-AppleTalk-Network" => 38,
        "Framed-AppleTalk-Zone" => 39,
        "Acct-Status-Type" => 40,
        "Acct-Delay-Time" => 41,
        "Acct-Input-Octets" => 42,
        "Acct-Output-Octets" => 43,
        "Acct-Session-Id" => 44,
        "Acct-Authentic" => 45,
        "Acct-Session-Time" => 46,
        "Acct-Input-Packets" => 47,
        "Acct-Output-Packets" => 48,
        "Acct-Terminate-Cause" => 49,
        "Acct-Multi-Session-Id" => 50,
        "Acct-Link-Count" => 51,
        "Acct-Input-Gigawords" => 52,
        "Acct-Output-Gigawords" => 53,
        "Event-Timestamp" => 55,
        "Egress-VLANID" => 56,
        "Ingress-Filters" => 57,
        "Egress-VLAN-Name" => 58,
        "User-Priority-Table" => 59,
        "CHAP-Challenge" => 60,
        "NAS-Port-Type" => 61,
        "Port-Limit" => 62,
        "Login-LAT-Port" => 63,
        "Tunnel-Type" => 64,
        "Tunnel-Medium-Type" => 65,
        "Tunnel-Client-Endpoint" => 66,
        "Tunnel-Server-Endpoint" => 67,
        "Acct-Tunnel-Connection" => 68,
        "Tunnel-Password" => 69,
        "ARAP-Password" => 70,
        "ARAP-Features" => 71,
        "ARAP-Zone-Access" => 72,
        "ARAP-Security" => 73,
        "ARAP-Security-Data" => 74,
        "Password-Retry" => 75,
        "Prompt" => 76,
        "Connect-Info" => 77,
        "Configuration-Token" => 78,
        "EAP-Message" => 79,
        "Message-Authenticator" => 80,
        "Tunnel-Private-Group-ID" => 81,
        "Tunnel-Assignment-ID" => 82,
        "Tunnel-Preference" => 83,
        "ARAP-Challenge-Response" => 84,
        "Acct-Interim-Interval" => 85,
        "Acct-Tunnel-Packets-Lost" => 86,
        "NAS-Port-Id" => 87,
        "Framed-Pool" => 88,
        "CUI" => 89,
        "Tunnel-Client-Auth-ID" => 90,
        "Tunnel-Server-Auth-ID" => 91,
        "NAS-Filter-Rule" => 92,
        "Originating-Line-Info" => 94,
        "NAS-IPv6-Address" => 95,
        "Framed-Interface-Id" => 96,
        "Framed-IPv6-Prefix" => 97,
        "Login-IPv6-Host" => 98,
        "Framed-IPv6-Route" => 99,
        "Framed-IPv6-Pool" => 100,
        "Error-Cause" => 101,
        "EAP-Key-Name" => 102,
        "Digest-Response" => 103,
        "Digest-Realm" => 104,
        "Digest-Nonce" => 105,
        "Digest-Response-Auth" => 106,
        "Digest-Nextnonce" => 107,
        "Digest-Method" => 108,
        "Digest-URI" => 109,
        "Digest-Qop" => 110,
        "Digest-Algorithm" => 111,
        "Digest-Entity-Body-Hash" => 112,
        "Digest-CNonce" => 113,
        "Digest-Nonce-Count" => 114,
        "Digest-Username" => 115,
        "Digest-Opaque" => 116,
        "Digest-Auth-Param" => 117,
        "Digest-AKA-Auts" => 118,
        "Digest-Domain" => 119,
        "Digest-Stale" => 120,
        "Digest-HA1" => 121,
        "SIP-AOR" => 122,
        "Delegated-IPv6-Prefix" => 123,
        "MIP6-Feature-Vector" => 124,
        "MIP6-Home-Link-Prefix" => 125,
        "Operator-Name" => 126,
        "Location-Information" => 127,
        "Location-Data" => 128,
        "Basic-Location-Policy-Rules" => 129,
        "Extended-Location-Policy-Rules" => 130,
        "Location-Capable" => 131,
        "Requested-Location-Info" => 132,
        "Framed-Management-Protocol" => 133,
        "Management-Transport-Protection" => 134,
        "Management-Policy-Id" => 135,
        "Management-Privilege-Level" => 136,
        "PKM-SS-Cert" => 137,
        "PKM-CA-Cert" => 138,
        "PKM-Config-Settings" => 139,
        "PKM-Cryptosuite-List" => 140,
        "PKM-SAID" => 141,
        "PKM-SA-Descriptor" => 142,
        "PKM-Auth-Key" => 143,
        "DS-Lite-Tunnel-Name" => 144,
        "Mobile-Node-Identifier" => 145,
        "Service-Selection" => 146,
        "PMIP6-Home-LMA-IPv6-Address" => 147,
        "PMIP6-Visited-LMA-IPv6-Address" => 148,
        "PMIP6-Home-LMA-IPv4-Address" => 149,
        "PMIP6-Visited-LMA-IPv4-Address" => 150,
        "PMIP6-Home-HN-Prefix" => 151,
        "PMIP6-Visited-HN-Prefix" => 152,
        "PMIP6-Home-Interface-ID" => 153,
        "PMIP6-Visited-Interface-ID" => 154,
        "PMIP6-Home-IPv4-HoA" => 155,
        "PMIP6-Visited-IPv4-HoA" => 156,
        "PMIP6-Home-DHCP4-Server-Address" => 157,
        "PMIP6-Visited-DHCP4-Server-Address" => 158,
        "PMIP6-Home-DHCP6-Server-Address" => 159,
        "PMIP6-Visited-DHCP6-Server-Address" => 160,
        "PMIP6-Home-IPv4-Gateway" => 161,
        "PMIP6-Visited-IPv4-Gateway" => 162,
        "EAP-Lower-Layer" => 163,
        "GSS-Acceptor-Service-Name" => 164,
        "GSS-Acceptor-Host-Name" => 165,
        "GSS-Acceptor-Service-Specifics" => 166,
        "GSS-Acceptor-Realm-Name" => 167,
        "Framed-IPv6-Address" => 168,
        "DNS-Server-IPv6-Address" => 169,
        "Route-IPv6-Information" => 170,
        "Delegated-IPv6-Prefix-Pool" => 171,
        "Stateful-IPv6-Address-Pool" => 172,
        "IPv6-6rd-Configuration" => 173,
        "Allowed-Called-Station-Id" => 174,
        "EAP-Peer-Id" => 175,
        "EAP-Server-Id" => 176,
        "Mobility-Domain-Id" => 177,
        "Preauth-Timeout" => 178,
        "Network-Id-Name" => 179,
        "EAPoL-Announcement" => 180,
        "WLAN-HESSID" => 181,
        "WLAN-Venue-Info" => 182,
        "WLAN-Venue-Language" => 183,
        "WLAN-Venue-Name" => 184,
        "WLAN-Reason-Code" => 185,
        "WLAN-Pairwise-Cipher" => 186,
        "WLAN-Group-Cipher" => 187,
        "WLAN-AKM-Suite" => 188,
        "WLAN-Group-Mgmt-Cipher" => 189,
        "WLAN-RF-Band" => 190
    );

    /**
     * Gets the attribute name, from its Id
     * @var int $attr_id
     * @return string attribute name per RFC, or FALSE if doesn't exist
     */
    public function attributeToString($attr_id)
    {
        return array_search($attr_id,$this->_attributes); 
    }
}

